---
title: "The performance of widely used language models tasked with identifying the distribution responsible for generating simulated data"
author: "JE, TJ, RWW"
bibliography: "bibliography.bib"
nocite: |
     @*
format:
    html:
       theme: superhero
       fig-format: jpeg
       fig-dpi: 600
       fig-height: 6
       fig-width: 8
       embed-resources: true
---

# The Organization of the Website

Eaglesmith, Justus, Tim Johnson, and Robert W. Walker.  2025.  *The performance of widely used language models tasked with identifying the distribution responsible for generating simulated data.*

[The support document for the letter.](./Final-Prompt-Results/Replication-of-Letter.html)

[TLDR;](./Final-Prompt-Results/Basic-Analysis.html)

The directory `Final-Prompt-Results` contains [all the results](https://github.com/robertwwalker/LLM_Distributions/tree/main/Final-Prompt-Results).  They are organized hierarchically by model [0409-turbo, 0806, 0613, 1211] and then by distribution.

- The [0409-turbo page](./Final-Prompt-Results/0409-turbo/Complete.Analysis-0409.html)
- The [0806 page](./Final-Prompt-Results/0806/Complete.Analysis-0806.html)
- The [0613 page](./Final-Prompt-Results/0613/Complete.Analysis.html)
- The [1211 page](./Final-Prompt-Results/1211/index.html)


[A sample prompt](./Final-Prompt-Results/Prompt-1.html)

In each subdirectory, there are: 

- a series of .qmd files containing Combiner.  These combine the input and output files [in jsonl format] with the original .RData files.
- a series of .RData files with `Full` that represent the combined input, output and RData files.
- a series of .RData files with an R random generation function that store the original calls and data.
- a .R file containining Combiner that binds the rows of the Full data files.
- Two sets of .jsonl files: output contains the OpenAI responses and -Call-Revised.jsonl contains the batch files sent to OpenAI.

## Details

Taking the example of the beta distribution, there are three sets of results.

For `gpt-4o-2024-08-06`:

The results are combined in:  

+ [Beta(1,2)](Final-Prompt-Results/0806/beta-08-06/Beta-Combiner12-0806.html)
+ [Beta(2,2)](Final-Prompt-Results/0806/beta-08-06/Beta-Combiner22-0806.html)
+ [Beta(3,2)](Final-Prompt-Results/0806/beta-08-06/Beta-Combiner32-0806.html)
+ [Beta(4,2)](Final-Prompt-Results/0806/beta-08-06/Beta-Combiner42-0806.html)
+ [Beta(5,2)](Final-Prompt-Results/0806/beta-08-06/Beta-Combiner52-0806.html)

For `gpt-4-0613`:

The results are combined in:  

+ [Beta(1,2)](Final-Prompt-Results/0613/beta/Beta-Combiner12.html)
+ [Beta(2,2)](Final-Prompt-Results/0613/beta/Beta-Combiner22.html)
+ [Beta(3,2)](Final-Prompt-Results/0613/beta/Beta-Combiner32.html)
+ [Beta(4,2)](Final-Prompt-Results/0613/beta/Beta-Combiner42.html)
+ [Beta(5,2)](Final-Prompt-Results/0613/beta/Beta-Combiner52.html)

For `gpt-4-turbo-2024-04-09`:

The results are combined in:  

+ [Beta(1,2)](Final-Prompt-Results/0409-turbo/beta-turbo/Beta-Combiner12-0409.html)
+ [Beta(2,2)](Final-Prompt-Results/0409-turbo/beta-turbo/Beta-Combiner22-0409.html)
+ [Beta(3,2)](Final-Prompt-Results/0409-turbo/beta-turbo/Beta-Combiner32-0409.html)
+ [Beta(4,2)](Final-Prompt-Results/0409-turbo/beta-turbo/Beta-Combiner42-0409.html)
+ [Beta(5,2)](Final-Prompt-Results/0409-turbo/beta-turbo/Beta-Combiner52-0409.html)

Other results follow an identical pattern substituting the names of the distributions and parameters relevant in the given case, e.g. `Final-Prompt-Results/0409-turbo/beta-turbo/Beta-Combiner52-0409.html` becomes `Final-Prompt-Results/0409-turbo/poisson-turbo/Poisson-Combined-5-0409.html`

As the files make clear, the keys for merging the batch results and the batch queries are the unique-id's that we assign for each distribution/parameter/iteration.

# The Software Bibliography

{{< pdf softbib.pdf width=100% height=600 >}}

# References

```{r}
library(knitr)
library(quarto)
write_bib(names(sessionInfo()$otherPkgs), file="bibliography.bib")
```
