---
title: "Model: 1211"
format: html
---

The following results repeat the experiment with `gpt-5.2-2025-12-11`.

The individual results can be found in the separate directories.

+ [Beta](./beta-1211/)
+ [Binomial](./binomial-1211/)
+ [Chi-squared](./chisquare-1211/)
+ [Gamma](./gamma-1211/)
+ [Geometric](./geometric-1211/)
+ [Lognormal](./lognormal-1211/)
+ [Normal](./normal-1211/)
+ [Poisson](./poisson-1211/)
+ [Uniform](./uniform-1211/)

# Aggregate Results

```{r}
library(tidyverse)
library(gtExtras)
# Beta
load("./beta-1211/CompleteBeta.1211.RData")
Complete.Beta.1211$name <- "Beta"
Complete.Beta.1211 <- Complete.Beta.1211 |> mutate(Dist = paste0(name,"(",str_replace(str_remove(key, "rbeta-"),"-",","),")",sep=""))

# Binomial
load("./binomial-1211/Complete.Binomial.1211.RData")
Complete.Binomial.1211$name <- "Binomial"
Complete.Binomial.1211 <- Complete.Binomial.1211 |> mutate(Dist = paste0(name,"(",str_replace(str_remove(key, "rbinom-"),"-",","),")",sep=""))

# Chi-square
load("./chisquare-1211/CompleteChisq.1211.RData")
Complete.Chisq.1211$name <- "Chi-square"
Complete.Chisq.1211 <- Complete.Chisq.1211 |> mutate(Dist = paste0(name,"(",str_remove(key, "rchisq-"),")",sep=""))


# Gamma
load("./gamma-1211/CompleteGamma.1211.RData")
Complete.Gamma.1211$name <- "Gamma"
Complete.Gamma.1211 <- Complete.Gamma.1211 |> mutate(Dist = paste0(name,"(",str_replace(str_remove(key, "rgamma-"),"-",","),")",sep=""))

# Geometric
load("./geometric-1211/Complete.Geometric.1211.RData")
Complete.Geometric.1211$name <- "Geometric"
Complete.Geometric.1211 <- Complete.Geometric.1211 |> mutate(Dist = paste0(name,"(",str_remove(key, "rgeom-"),")",sep=""))

# Lognormal
load("./lognormal-1211/CompleteLognormal.1211.RData")
Complete.Lognormal.1211$name <- "Lognormal"
Complete.Lognormal.1211 <- Complete.Lognormal.1211 |> mutate(Dist = paste0(name,"(",str_replace(str_remove(key, "rlnorm-"),"-",","),")",sep=""))

# Normal
load("./normal-1211/CompleteNormal.1211.RData")
Complete.Normal.1211$name <- "Normal"
Complete.Normal.1211 <- Complete.Normal.1211 |> mutate(Dist = paste0(name,"(",str_replace(str_remove(key, "rnorm-"),"-",","),")",sep=""))

# Poisson
load("./poisson-1211/CompletePoisson.1211.RData")
Complete.Poisson.1211$name <- "Poisson"
Complete.Poisson.1211 <- Complete.Poisson.1211 |> mutate(Dist = paste0(name,"(",str_remove(key, "rpois-"),")",sep=""))

# Uniform
load("./uniform-1211/Complete.Uniform.1211.RData")
Complete.Uniform.1211$name <- "Uniform"
Complete.Uniform.1211 <- Complete.Uniform.1211 |> mutate(Dist = paste0(name,"[",str_replace(str_remove(key, "runif-"),"-",","),"]",sep=""))

# Bind Together
Complete.Data.1211 <- dplyr::bind_rows(Complete.Beta.1211, Complete.Binomial.1211, Complete.Chisq.1211, Complete.Gamma.1211, Complete.Geometric.1211, Complete.Lognormal.1211, Complete.Normal.1211, Complete.Poisson.1211, Complete.Uniform.1211)

# Create size and Full Distribution
Complete.Data.1211 <- Complete.Data.1211 |> rowwise() |> mutate(Size = length(data))
Complete.Data.1211 <- Complete.Data.1211 |> mutate(Full.Dist = paste0(Dist,"-",Size),sep="")
# Save Compiled file
save(Complete.Data.1211, file="Complete.Data.All.1211.RData")
```

## Collate Complete Files

```{r}
load("~/Nextcloud/LLM_Distributions/Final-Prompt-Results/Complete.Data.All.0409.RData")
load("~/Nextcloud/LLM_Distributions/Final-Prompt-Results/Complete.Data.All.0613.RData")
load("~/Nextcloud/LLM_Distributions/Final-Prompt-Results/Complete.Data.All.0806.RData")
load("~/Nextcloud/LLM_Distributions/Final-Prompt-Results/Complete.Data.All.1211.RData")
Complete.Data.01.2026 <- bind_rows(Complete.Data.0409, Complete.Data.0613, Complete.Data.0806, Complete.Data.1211)
```


## Results

```{r FirstTab}
Complete.Data.01.2026$Fresh.Outcome <- c(1:196000) %>% map_chr(., function(x) {Complete.Data.01.2026$response$body$choices[[x]]$message$content})
Complete.Data.01.2026$model <- Complete.Data.01.2026$body$model
Complete.Data.01.2026 |> group_by(Fresh.Outcome, model) |> summarise(Count = n()) |>  ungroup() |> pivot_wider(names_from = model, values_from = Count) |> gt()
```

## Cleaned a bit

```{r CleanTab}
Complete.Data.01.2026 <- Complete.Data.01.2026 |> 
  mutate(Outcome = case_match(Fresh.Outcome, 
                              c("arcsine","Arcsine") ~ "Arcsine",
                              c("categorical","Categorical") ~ "Categorical",
                              c("exponential","Exponential") ~ "Exponential",
                              c("beta","Beta") ~ "Beta",
                              c("exgaussian","ExGaussian") ~ "ExGaussian",
                              c("Normal","normal") ~ "Normal",
                              c("binomial","Binomial") ~ "Binomial",
                              c("geometric","Geometric") ~ "Geometric",
                              c("gamma","Gamma") ~ "Gamma",                              c("Lognormal","lognormal","Log-Normal","Log-normal") ~ "Lognormal",
                              c("NegativeBinomial","Negative Binomial","NegBinomial","Negbinomial","negativebinomial","Negativebinomial") ~ "Negative Binomial",
                              c("Skewed","Skewnormal","SkewNormal","Skew-normal","Skew-right","Skewness","skewnormal")~ "Skewed",
                              c("Student","Studentt","Studentt","t")~ "Student's t", c("Uniform","uniform")~ "Uniform",
                              c("ZeroInflatedPoisson","ZeroinflatedPoisson","Zero-inflated","ZIP")~ "ZIP",
                              .default = Fresh.Outcome))
Complete.Data.01.2026 |> group_by(Outcome, model) |> summarise(Count = n()) |>  ungroup() |> pivot_wider(names_from = model, values_from = Count) |> gt()
```
