---
title: "Binomial 20 Results Processor"
format: html
---

I will begin by loading three things.  

1. the data that were stored from creating the batch file.

```{r, message=FALSE, warning=FALSE}
library(jsonlite)
library(tidyverse)
load("../rbinom-0.7-20.RData")
```

2. The queries

```{r}
Binom0.7.20Call <- stream_in(file("rbinom-0.7-20-Call-Revised-0409.jsonl"))
```

3. The Results

```{r}
Binom0.7.20Result <- stream_in(file("rbinom-0.7-20_0409_output.jsonl"))
```

## Merge the call and the result

```{r}
Binom.07.20.OpenAI <- left_join(Binom0.7.20Call,Binom0.7.20Result)
Full.Binom.07.20.0409 <- left_join(Binom0.7.20$params, Binom.07.20.OpenAI)
```

The file is saved as `Full.Binom.07.20.0409.RData`.

Put the result in the params file.

```{r}
Full.Binom.07.20.0409$Outcome <- map_chr(Binom0.7.20$params$iter, function(x) { unlist(Binom0.7.20Result$response$body$choices[[x]][[2]][2]) })
table(Full.Binom.07.20.0409$Outcome)
```

```{r}
save(Full.Binom.07.20.0409, file="Full.Binom.07.20.0409.RData")
```

