---
title: "Complete Results Analysis"
author: "Robert W. Walker"
date: "11/25/2024"
format:
  html:
     self-contained: true
     theme: superhero
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.retina=3)
library(tidyverse)
```

Each result should be identical in structure by design.

```{r}
load("Complete.Binomial.RData")
Complete.Binomial$name <- "Binomial"
Complete.Binomial <- Complete.Binomial |> mutate(Dist = paste0(name,"(",str_replace(str_remove(key, "rbinom-"),"-",","),")",sep=""))
load("CompleteGamma.RData")
Complete.Gamma$name <- "Gamma"
Complete.Gamma <- Complete.Gamma |> mutate(Dist = paste0(name,"(",str_replace(str_remove(key, "rgamma-"),"-",","),")",sep=""))
load("Complete.Uniform.RData")
Complete.Uniform$name <- "Uniform"
Complete.Uniform <- Complete.Uniform |> mutate(Dist = paste0(name,"[",str_replace(str_remove(key, "runif-"),"-",","),"]",sep=""))
load("CompleteBeta.RData")
Complete.Beta$name <- "Beta"
Complete.Beta <- Complete.Beta |> mutate(Dist = paste0(name,"(",str_replace(str_remove(key, "rbeta-"),"-",","),")",sep=""))
load("CompletePoisson.RData")
Complete.Poisson$name <- "Poisson"
Complete.Poisson <- Complete.Poisson |> mutate(Dist = paste0(name,"(",str_remove(key, "rpois-"),")",sep=""))
load("CompleteNormal.RData")
Complete.Normal$name <- "Normal"
Complete.Normal <- Complete.Normal |> mutate(Dist = paste0(name,"(",str_replace(str_remove(key, "rnorm-"),"-",","),")",sep=""))
load("CompleteChisq.RData")
Complete.Chisq$name <- "Chi-square"
Complete.Chisq <- Complete.Chisq |> mutate(Dist = paste0(name,"(",str_remove(key, "rchisq-"),")",sep=""))
load("CompleteLognormal.RData")
Complete.Lognormal$name <- "Lognormal"
Complete.Lognormal <- Complete.Lognormal |> mutate(Dist = paste0(name,"(",str_replace(str_remove(key, "rlnorm-"),"-",","),")",sep=""))
load("Complete.Geometric.RData")
Complete.Geometric$name <- "Geometric"
Complete.Geometric <- Complete.Geometric |> mutate(Dist = paste0(name,"(",str_remove(key, "rgeom-"),")",sep=""))
Complete.Data <- dplyr::bind_rows(Complete.Beta, Complete.Binomial, Complete.Poisson, Complete.Uniform, Complete.Normal,Complete.Chisq,Complete.Gamma,Complete.Geometric, Complete.Lognormal)
Complete.Data <- Complete.Data |> rowwise() |> mutate(Size = length(data))
Complete.Data <- Complete.Data |> mutate(Full.Dist = paste0(Dist,"-",Size),sep="")
```


## Tables

```{r}
table(Complete.Data$Full.Dist)
```

```{r}
save(Complete.Data, file="Complete.Data.All.RData")
```
